---
#
#    Debian 7 (wheezy) Redis32 Cache System (docker-compose.yml)
#    Copyright (C) 2016-2017 Stafli
#    Luís Pedro Algarvio
#    This file is part of the Stafli Application Stack.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# For Docker Compose v2+ only
version: '2'

#
# Services
#
services:

  cache_redis32_debian7:
    labels:
      - "description=$PROJECT_NAME, $PROJECT_DESCRIPTION"
      - "maintainer=$PROJECT_AUTHORS_LPALGARVIO_NAME <$PROJECT_AUTHORS_LPALGARVIO_EMAIL>"
      - "org.label-schema.schema-version=1.0.0-rc.1"
      - "org.label-schema.name=$PROJECT_NAME"
      - "org.label-schema.description=$PROJECT_DESCRIPTION"
      - "org.label-schema.keywords=$PROJECT_KEYWORDS"
      - "org.label-schema.url=$PROJECT_URL"
      - "org.label-schema.license=$PROJECT_LICENSE"
      - "org.label-schema.vendor-name=$PROJECT_VENDOR_NAME"
      - "org.label-schema.vendor-email=$PROJECT_VENDOR_EMAIL"
      - "org.label-schema.vendor-website=$PROJECT_VENDOR_WEBSITE"
      - "org.label-schema.authors.lpalgarvio.name=$PROJECT_AUTHORS_LPALGARVIO_NAME"
      - "org.label-schema.authors.lpalgarvio.email=$PROJECT_AUTHORS_LPALGARVIO_EMAIL"
      - "org.label-schema.authors.lpalgarvio.homepage=$PROJECT_AUTHORS_LPALGARVIO_HOMEPAGE"
      - "org.label-schema.authors.lpalgarvio.role=$PROJECT_AUTHORS_LPALGARVIO_ROLE"
      - "org.label-schema.registry-url=$REGISTRY_URL"
      - "org.label-schema.vcs-url=$VCS_URL"
      - "org.label-schema.vcs-ref=$VCS_REF"
      - "org.label-schema.vcs-branch=$VCS_BRANCH"
      - "org.label-schema.os-id=$OS_ID"
      - "org.label-schema.os-version-id=$OS_VERSION_ID"
      - "org.label-schema.os-architecture=$BUILD_ARCH"
      - "org.label-schema.version=$BUILD_VERSION"
      - "org.label-schema.build-date=$BUILD_DATE"
    image: "${IMAGE_URL_PREFIX}:${IMAGE_TAG_PREFIX}${DISTRO_DEBIAN7_VERSION}_${OS_RELEASE_ID}"
    build:
      context: "./dockerfiles"
      dockerfile: "${IMAGE_TAG_PREFIX}${DISTRO_DEBIAN7_VERSION}.dockerfile"
      args:
        app_redis_user: "redis"
        app_redis_group: "redis"
        app_redis_home: "/var/lib/redis"
        app_redis_loglevel: "notice"
        app_redis_listen_addr: "0.0.0.0"
        app_redis_listen_port: "6379"
        app_redis_listen_timeout: "5"
        app_redis_listen_keepalive: "60"
        app_redis_limit_backlog: "256"
        app_redis_limit_concurent: "256"
        app_redis_limit_memory: "134217728"
    logging:
      driver: "json-file"
    volumes:
      - cache_redis32_debian7_data:/var/lib/redis
    ports:
      - "6379"
    working_dir: "/tmp"
    command: "/usr/bin/supervisord -c /etc/supervisor/supervisord.conf --nodaemon"

#
# Volumes
#
volumes:
  cache_redis32_debian7_data:
    driver: "local"

